### ISSUE TITLE
Debian 11 image not booting

### ISSUE THREAD

**Issue by jdeinum** [embeddedTS/linux-lts#29]
Note: I am not sure where the best place to submit this issue is. I hope this is ok :)

Using the stock debian 11 image with Linux-4.9.11-gcd63e41f54b3  seems to have some problems booting up. The TS4900 is on a custom board, and in production uses a custom device tree (just needed to add another SPI device).  For this test, just the default device tree is used.

# Steps to Reproduce

```
sudo mkfs.ext3 /dev/sda1 # or whatever your device is
wget -P /tmp https://files.embeddedts.com/ts-socket-macrocontrollers/ts-4900-linux/distribution/debian/debian-armhf-bullseye-latest.tar.bz2
sudo mkdir -p /mnt/sdcard
sudo mount /dev/sda1 /mnt/sdcard
sudo tar xvf /tmp/debian-armhf-bullseye-latest.tar.bz2 -C /mnt/sdcard
sudo umount /mnt/sdcard
```

# The Errors

```
[    3.778459] imx6q-pcie 1ffc000.pcie: phy link never came up
[    3.781559] imx6q-pcie 1ffc000.pcie: failed to initialize host
[    4.215991] snvs-secvio 20cc000.caam-snvs: can't get snvs clock
[    4.244942] imx_epdc_fb 20f4000.epdc: can't get/select pinctrl
[    5.307452] cgroup: cgroup2: unknown option "nsdelegate,memory_recursiveprot"
[    5.316702] cgroup: cgroup2: unknown option "nsdelegate"
...
[    5.649441] systemd[1]: System cannot boot: Missing /etc/machine-id and /etc is mounted read-only.
[    5.658546] systemd[1]: Booting up is supported only when:
[    5.664125] systemd[1]: 1) /etc/machine-id exists and is populated.
[    5.670482] systemd[1]: 2) /etc/machine-id exists and is empty.
[    5.676450] systemd[1]: 3) /etc/machine-id is missing and /etc is writable.
```

And when trying to login as root:

```
tsimx6 login: root
login: PAM Failure, aborting: Critical er�
Debian GNU/Linux 11 tsimx6 ttymxc0
```

# Things I've tried
I compiled the 5.10.y kernel and tried using that instead, same results. 

I've also reseated the ts4900 into its socket, incase it was a connection issue.

**Comment by markfeathers** [comment]
Sorry about that, it looks like a bug in the image released yesterday. I've rolled that back for now. These are generated by scripts and nothing but a kernel bump had occurred, but it looks like something in a Debian package changed for how we generate new images. This last image only upgraded the kernel to improve compatibility with a new TS-TPC-7990 hardware release rather than any intentional Debian package changes.  I'll reupload a new image when this is addressed.
