### ISSUE TITLE
TS-TPC-8390 i2c-gpio should set delay-us

### ISSUE THREAD

**Issue by MarkFeatherston** [embeddedTS/linux-lts#38]
- i2c-gpio,delay-us: delay between GPIO operations (may depend on each platform)

https://github.com/embeddedTS/linux-lts/blob/linux-5.10.y/arch/arm/boot/dts/imx6qdl-ts4900-ts8390.dtsi#L68

We may want to review our current i2c-gpio usages to make sure we're not running this too fast with various controllers.

**Comment by ts-kris** [comment]
A change like this is unnecessary.

`pdata->udelay` is derived from this option:
https://github.com/embeddedTS/linux-lts/blob/d73e3bb8f6196b3cff6161739d393402554a55bb/drivers/i2c/busses/i2c-gpio.c#L303-L308

If not provided (and we don't set SCL is output only which we do not) then the driver defaults to 5 us or ~100 kHz bus speed
https://github.com/embeddedTS/linux-lts/blob/d73e3bb8f6196b3cff6161739d393402554a55bb/drivers/i2c/busses/i2c-gpio.c#L423-L428

<br>
<br>
<br>
<br>

This is true in 6.6 as well:

https://github.com/embeddedTS/linux-lts/blob/46a79002dad4c2d356d8ad9cf762e26731e304e3/drivers/i2c/busses/i2c-gpio.c#L304-L309
https://github.com/embeddedTS/linux-lts/blob/46a79002dad4c2d356d8ad9cf762e26731e304e3/drivers/i2c/busses/i2c-gpio.c#L431-L436
